### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by rabbpigPan** [f0rb1dd3n/Reptile#11]
**After execute  apt-get install linux-headers-$(uname -r),it shows**

Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-headers-4.4.0-116-generic is already the newest version (4.4.0-116.140).
0 upgraded, 0 newly installed, 0 to remove and 158 not upgraded.

**then I execute ./installer.sh install,it shows** 

############################################################################
############################################################################
writen by: F0rb1dd3n

Compiling... DONE!
Copying binaries to /reptile... DONE!
Installing... insmod: ERROR: could not insert module /reptile/reptile.ko: Invalid module format
ERROR!

**Additional information about the system:**
Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018

**Comment by f0rb1dd3n** [comment]
Hello man,

try to comment the line 107 of the installer.sh 
```
strip bin/$MODULE.ko
```
run it again and tell me if the problem was solved. I am waiting your test.

See ya!

**Comment by rabbpigPan** [comment]
Hello, I try it and it doesn't work.
Another question, how to hide specific files and directories?

**Comment by f0rb1dd3n** [comment]
Hello, I set up a VM to do this test, and Reptile worked fine. I suggest you to comment the line `strip bin/$MODULE.ko` that I told you (I will commit the changes to comment this line, just update), run `./install.sh build` then run `insmod bin/reptile.ko`. Maybe you must have to do manual tests.

Without strip, Reptile should run normally. 

To hide specific files and directories you just have to rename the file or directory to some name with the word **reptile** in the beginning. Example: reptile_folder, reptile_file, etc. The installer.sh already create a folder `/reptile` that will be hidden and copy the scripts to this with the prologue `reptile_` that will hidden those files. But if you run those scripts like `/reptile/reptile_knock` that will run properly.

I think I helped you. Let me know if you have more trouble with it.

F0rb1dd3n

**Comment by rabbpigPan** [comment]
Hello, I have downloaded the latest source code and done manual tests by following your suggestion, but it failed again. Anyway, thanks for your great help.

**Comment by f0rb1dd3n** [comment]
Hey man, just few questions:

- this machine is yours (for tests) or is "on the wild". (if you dont wanna answer that here, feel free to mail me).
- if this machine is yours, did you rebooted this system?
- this kind of problem appears when you update the kernel version and dont reboot. **Make sure you are root** and try to do the follow:
```
apt-get update && apt-get upgrade -y
reboot
apt-get dist-upgrade -y
reboot again
apt-get install linux-headers-$(uname -r)
reboot again just to get sure, then run `installer.sh install`
```
If this problem still persist, try to load the module, run `dmesg` command and show me the output (not at all, just the end of the dump when you try to load the module).

Let me know if you figure it out. Feel free to mail me if you need. ;)

F0b1dd3n

**Comment by rabbpigPan** [comment]
Sorry for the delay. I reboot the system and it works now.
thx.

**Comment by f0rb1dd3n** [comment]
hahahahaha, 

Nice. I am glad this problem was solved. Enjoy Reptile!
