### ISSUE TITLE
Unexported vfs_read

### ISSUE THREAD

**Issue by sempervictus** [f0rb1dd3n/Reptile#13]
Linus [un-exported vfs_read](https://github.com/torvalds/linux/commit/bd8df82be66698042d11e7919e244c8d72b042ca) preventing use on 4.14+

**Comment by f0rb1dd3n** [comment]
Thanks for reporting that. I will consider that to the next commit!

**Comment by f0rb1dd3n** [comment]
@sempervictus, 

did you see the guys is normally solve this with `kernel_read` function. I havent the opportunity to test this. So, do you know if it is really works? Is just to replace these functions, or no?

Thanks bro

**Comment by f0rb1dd3n** [comment]
fixed at [0f0aab2](https://github.com/f0rb1dd3n/Reptile/commit/0f0aab26353327ca733b918d8c3a5d2045dd1568)
