### ISSUE TITLE
New feature: Reverse root shell

### ISSUE THREAD

**Issue by David-Reguera-Garcia-Dreg** [f0rb1dd3n/Reptile#14]
Add a reverse-root-shell (each X time) - with certificate - using a DGA and/or IP/DOMAIN.

**Comment by f0rb1dd3n** [comment]
That is a nice idea, I will consider that. But not so advanced. I prefer to keep 1337 versions in priv8. hahaha.

**Comment by f0rb1dd3n** [comment]
@David-Reguera-Garcia-Dreg,

Reverse-root-shell is now written. You can configure it at `start.sh` script.

**Comment by David-Reguera-Garcia-Dreg** [comment]
nice feature! :-)
