### ISSUE TITLE
missed reference.

### ISSUE THREAD

**Issue by dnoiz1** [f0rb1dd3n/Reptile#20]
Hi, did you want to add my blog post to your list of references?
https://www.google.com.au/search?q="unsigned+int+magic_packet_hook"

Thanks.

**Comment by f0rb1dd3n** [comment]
Yeah man, sorry about that, I forgot in update this. Now, I put this references on my last commit. 

Thank you for your blog post!

**Comment by dnoiz1** [comment]
fixed in https://github.com/f0rb1dd3n/Reptile/commit/b5a4f1831b77e5b4d1418590ed2556ffaa8dcc75
