### ISSUE TITLE
Unsafe skb handling

### ISSUE THREAD

**Issue by milabs** [f0rb1dd3n/Reptile#22]
`data = (char *)((unsigned char *)icmp_header + sizeof(struct icmphdr));`
`data = (char *)((unsigned char *)tcp_header + sizeof(struct tcphdr));`
`data = (char *)((unsigned char *)udp_header + sizeof(struct udphdr));`

[skb_header_pointer()](https://elixir.bootlin.com/linux/latest/source/include/linux/skbuff.h#L3335) must be used along with local on-stack copy of `skb->data` portion... 

See the example:
https://elixir.bootlin.com/linux/latest/source/net/bridge/netfilter/ebt_ip.c#L36

**Comment by f0rb1dd3n** [comment]
Can we close this and the another one?

**Comment by f0rb1dd3n** [comment]
fixed in [f667770](https://github.com/f0rb1dd3n/Reptile/commit/f667770be172a93bc08f89d5ad281711e9a2d4ac)
