### ISSUE TITLE
Can't remove 

### ISSUE THREAD

**Issue by fcafra** [f0rb1dd3n/Reptile#23]
Hi, Im a gay ... :) 
so, when launch ./installer.sh remove I get this 
Uninstalling... rmmod: ERROR: Module rep_mod is in use

Another Info:
On 4.15.0-kali3-amd64
lsmod | grep rep_mod
rep_mod                20480  1

/sbin/modinfo reptile
filename:       /lib/modules/4.15.0-kali3-amd64/kernel/drivers/PulseAudio/reptile/reptile.ko
description:    Reptile - A linux LKM rootkit
author:         F0rb1dd3n - ighor@intruder-security.com
license:        GPL
depends:        
retpoline:      Y
name:           rep_mod
vermagic:       4.15.0-kali3-amd64 SMP mod_unload modversions 

rmmod /lib/modules/4.15.0-kali3-amd64/kernel/drivers/PulseAudio/reptile/reptile.ko
rmmod: ERROR: Module reptile is not currently loaded

How to uninstall please ?

**Comment by f0rb1dd3n** [comment]
Hello, 

try the follow: 

`rm -f /etc/modules && depmod && reboot`

After that, and after reboot, reptile won't be loaded. To fully clean your machine remove `/reptile` and `/lib/modules/4.15.0-kali3-amd64/kernel/drivers/PulseAudio/reptile`.

When this kind of error occurs, you also can reboot the machine and wait the module load again to run uninstaller.

I hope I helped you,

403

**Comment by fcafra** [comment]
@f0rb1dd3n  Thanks 403, you help me.  :+1:

**Comment by fcafra** [comment]
Oh Yes, Sorry.
