### ISSUE TITLE
I test on Centos6.5, Compiling Error

### ISSUE THREAD

**Issue by Hacker-One** [f0rb1dd3n/Reptile#24]
uname -a
`Linux root 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
`
Compiling Error
`############################################################################
############################################################################
written by: F0rb1dd3n
SELinux config found on system!
Checking SELinux status... clear

Hide name (will be used to hide dirs/files) (default: reptile): 
Auth token to port-knocking (default: hax0r): 
Backdoor password (default: s3cr3t): 
Tag name that hide file contents (default: reptile): 
Source port to port-knocking (default: 666): 
TCP port to port-knocking (default: 80): 
UPD port to port-knocking (default: 53): 

Hide name: reptile
Token: hax0r
Backdoor password: s3cr3t
SRC port: 666
TCP port: 80
UDP port: 53
TAGs to hide file contents: 

#<reptile>
content to be hidden
#</reptile>

Configuring... DONE!
Compiling... ERROR!
`

**Comment by corefx** [comment]
Hi,
make sure that the following packages are installed:
`yum install gcc make elfutils-devel.x86_64 kernel-devel-`uname -r` `

**Comment by Hacker-One** [comment]
Those dependent packages have been installed.
OK, I noticed another branch about "didn't work on Centos 6"

**Comment by Hacker-One** [comment]
I testing on Centos 6.6，that's OK
`uname -a 
Linux Centos 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Apr 11 17:13:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

but didn't work on Centos 6.5 
`uname -a
Linux Centos 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pbr3s** [comment]
Edit the lines 185 and 186 on the `installer.sh`
`make all  && \`
`make clean && \`
This way the installer will return more info about whats going on in the compiler section

**Comment by Hacker-One** [comment]
@f0rb1dd3n That'is OK follow the above configuration.
`[root@biu sbin]# make
gcc -O -W -Wall -o client  pel.c aes.c sha1.c client.c
gcc -O -W -Wall -o shell pel.c aes.c sha1.c shell.c -lutil -DLINUX
gcc -Wall r00t.c -o r00t
strip client shell r00t
cp client shell r00t ../bin
`

`[root@biu sbin]# ll ../bin
total 128
-rwxr-xr-x 1 root root 64584 May 25 05:58 client
-rwxr-xr-x 1 root root  4912 May 25 05:58 r00t
-rwxr-xr-x 1 root root 56160 May 25 05:58 shell`

**Comment by Hacker-One** [comment]
@pbr3s in install.sh partial content about lines

183         make all > /dev/null 2>&1 && \
184         make clean > /dev/null 2>&1 && \

**Comment by f0rb1dd3n** [comment]
@Hacker-One 

man, put `put config.h` but do `make` in main folder. Cause `rep_mod.c` uses that config file too.

**Comment by f0rb1dd3n** [comment]
@Hacker-One,

pelase run `yum install kernel-devel -y && reboot` and try to `make` again.

**Comment by Hacker-One** [comment]
After the above operation,keeps making the same mistake....

**Comment by f0rb1dd3n** [comment]
It seems you don't have kernel headers... I don't know why. Try to run `yum update` and reinstall headers. I will think how we can figure it out...

**Comment by Hacker-One** [comment]
Maybe you are right，my system lost kernel Symbol file. I will rebuild this kernel.

**Comment by f0rb1dd3n** [comment]
@Hacker-One,

did you solve this issue?

**Comment by Hacker-One** [comment]
yes,It was just like you said.
Thanks
