### ISSUE TITLE
What parameter specifies the remote port?

### ISSUE THREAD

**Issue by ly24cx** [f0rb1dd3n/Reptile#26]
rt

**Comment by f0rb1dd3n** [comment]
You don't need to specify, the client will be compiled with this port as a constant.

**Comment by f0rb1dd3n** [comment]
@ly24cx,

I just have update client to receive source port and remote port as parameter. Now you can use client for any configuration without recompiling. So, you can use `-r` to remote port and `-q` to source port. 

Look if it solve your issue, and close this. 

;)

**Comment by ly24cx** [comment]
thanks
