### ISSUE TITLE
The driver mod don't load when system reboot

### ISSUE THREAD

**Issue by Hacker-One** [f0rb1dd3n/Reptile#27]
I test on centos that The driver mod don't load when system reboot

**Comment by f0rb1dd3n** [comment]
Are you using latest version? I have merged a pull request that fixed that!

**Comment by Hacker-One** [comment]
when I again install this LKM that the system will crash after LKM have installed on system.

**Comment by f0rb1dd3n** [comment]
could you show me the stacktrace? I have tested on CentOS and Reptile works fine, without crashing.

What system are you using? I will try to reproduce that to see what is happening. :)

**Comment by Hacker-One** [comment]
`Linux Centos 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Apr 11 17:13:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
![image](https://user-images.githubusercontent.com/14013299/40647837-76363d96-635f-11e8-85fa-e8841fd1718f.png)
when I again install this LKM that the system will crash and ssh disconnected after LKM have installed on system.

**Notice:**  Don't uninstall Reptile and again install Reptile

**Comment by f0rb1dd3n** [comment]
I am trying to understand what is going on, cause I just tested on CentOS box and is working fine, even after uninstallation. If you can retrieve more information about that, it would be nice.

**Comment by f0rb1dd3n** [comment]
could you do the follow, please?

- open installer.sh and put `exit` at line 293
- run installer
- do `insmod /reptile/reptile.ko`
- run `dmesg`
- and put here the final of the dump (see if there is some crash)

**Comment by f0rb1dd3n** [comment]
@Hacker-One,

Hey man, there is a crash that I working in! I am just little busy to fix this code, but I will.

thx

**Comment by f0rb1dd3n** [comment]
@Hacker-One,

can you test Reptile now, the last update can fixed your problem! ;)

**Comment by Hacker-One** [comment]
OK,I test that's ok.
