### ISSUE TITLE
GID bruteforcing detection

### ISSUE THREAD

**Issue by David-Reguera-Garcia-Dreg** [f0rb1dd3n/Reptile#28]
lsrootkit detects Reptile with a simple GID bruteforcing.

https://github.com/David-Reguera-Garcia-Dreg/lsrootkit

![cfe047bc-78c9-42c0-a0b7-e61e351b330e](https://user-images.githubusercontent.com/9882181/40684880-eb47d5da-6392-11e8-8a38-ea5245c406f1.jpg)

**Comment by f0rb1dd3n** [comment]
very nice job man, I already know that is the weakness of Reptile. Maybe update and change things to avoid detection, but since this rootkit is public, always have a way to detect, maybe I keep avoid of detection in priv8. hahaha

I took a look at your code and that is very nice, congrats.

**Comment by f0rb1dd3n** [comment]
hey man, 

did you have tested with last version of Reptile, I am running your code and I didnt have caught with that yet. But even that is fail, I need to change get root with setreuid hook. ;)

**Comment by David-Reguera-Garcia-Dreg** [comment]
the scanning can take hours, be very patient x)

**Comment by f0rb1dd3n** [comment]
@David-Reguera-Garcia-Dreg,

maybe my lazy update took Reptile undetectable by lsrootkit. ;)

but, I know you can detect it in other ways (perhaps using `kill`), maybe I need to stop being lazy... hahaha

**Comment by David-Reguera-Garcia-Dreg** [comment]
add a kill bruteforcing is in my TO-DO x)
