### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by cryptosk** [f0rb1dd3n/Reptile#29]
I would love to see these features implemented soon: 

Hide CPU usage for specified processes : bounty 0.2btc
Hide iptables rules via netfilter hooks - bounty 0.1btc
Execute command at specified time directly via module (not using third party apps like cron) - bounty 0.1btc

Let me know if you are willing to work on this and i will forward my onion contact info.

**Comment by f0rb1dd3n** [comment]
yeah man, I do priv8 jobs. Mail me with your contact info. thx

**Comment by f0rb1dd3n** [comment]
@cryptosk, my e-mail: f0rb1dd3n@tuta.io

**Comment by cryptosk** [comment]
Email sent.
