### ISSUE TITLE
module_mutex should be taken while linking/unlinking

### ISSUE THREAD

**Issue by milabs** [f0rb1dd3n/Reptile#33]
https://github.com/f0rb1dd3n/Reptile/blob/2f13aacc32e5baa6456e984e8ff25eb153cfa2ab/rep_mod.c#L120

**Comment by f0rb1dd3n** [comment]
fixed at:

https://github.com/f0rb1dd3n/Reptile/blob/abd19e1139121db508e652c24a7b4d810526bc5f/rep_mod.c#L119


And thank you a lot for all these contributions. You are great man!!! 👍
