### ISSUE TITLE
blocking required while iterating over process list

### ISSUE THREAD

**Issue by milabs** [f0rb1dd3n/Reptile#34]
https://github.com/f0rb1dd3n/Reptile/blob/2f13aacc32e5baa6456e984e8ff25eb153cfa2ab/rep_mod.c#L135

rcu_read_lock()
for_each_process() { ... }
rcu_read_unlock()

Or:

read_lock(&tasklist_lock)
for_each_process() { ... }
read_unlock(&tasklist_lock)

Also get_task_struct() required for returning tasks.

See [get_pid_task](https://elixir.bootlin.com/linux/latest/source/kernel/pid.c#L371)

**Comment by f0rb1dd3n** [comment]
fixed at:

https://github.com/f0rb1dd3n/Reptile/blob/abd19e1139121db508e652c24a7b4d810526bc5f/rep_mod.c#L140
