### ISSUE TITLE
setup.sh: offensive sentence [remove proposal].

### ISSUE THREAD

**Issue by PedroSFreitas** [f0rb1dd3n/Reptile#45]
You have a nice project, and judging by the stars it has, you should be very proud.
However, I propose the complete removal of [this line](https://github.com/f0rb1dd3n/Reptile/blob/master/setup.sh#L324) from the `setup.sh`.

It's very much offensive and without adding any value to your project. Don't you agree?

(_está dando bobeira aí amigão, de graça_).

**Comment by sav** [comment]
omg, seriously? so uncool. sorry I was following this project I ended up reading this lame PR. could not hold myself lol I bet Pedro is a ETHICAL hacker

**Comment by sav** [comment]
value to the project lol what value kid :> who gives a damn about value when you get #
