### ISSUE TITLE
add poison runlevel

### ISSUE THREAD

**Issue by vay3t** [f0rb1dd3n/Reptile#48]
watching some projects I found this. It would be interesting and helpful to be able to add utility "poison runlevel" for persistence.

https://github.com/powerofkernel/poisonRunlevel-v3

**Comment by f0rb1dd3n** [comment]
Hello @vay3t,

thank you for your hint. I will consider that for the next updates. :)

**Comment by f0rb1dd3n** [comment]
This way of persistence is discarted for now. Maybe I can consider that in the future if the current way fails.
