### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by corefx** [f0rb1dd3n/Reptile#49]
Hi,
Thanks for the beta version. I tried to compile it on Ubuntu 18.04.1 (64 bit) but I got following error:
<stdin>: In function 'runshell':
<stdin>:118:2: warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
/tmp/ccsXzAOl.o: In function `runshell':
:(.text+0x267): undefined reference to `openpty'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'reverse' failed
make[1]: *** [reverse] Error 1
make[1]: Leaving directory '/home/test/Reptile/sbin'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aliyuchang33** [comment]
Tried on Ubuntu 16.04 and 18.04.1. Both returned the same error message as above.

**Comment by f0rb1dd3n** [comment]
With this next commit, all should be going right on Ubuntu: [35fb60c](https://github.com/f0rb1dd3n/Reptile/commit/35fb60c8ef71f355bc203738698d6dc4cc4d881e)

I've tested on Ubuntu 18.04.1 LTS and now is all right.

Let me know if you guys will got more problem.

**Comment by corefx** [comment]
I can confirm that both bugs are now fixed. Thanks!
