### ISSUE TITLE
lsof: WARNING: unsupported format: /proc/net/tcp

### ISSUE THREAD

**Issue by corefx** [f0rb1dd3n/Reptile#52]
[test@test ~]$ lsof -i -n -P
lsof: WARNING: unsupported format: /proc/net/tcp
COMMAND   PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-n 448 systemd-network   19u  IPv4  15693      0t0  UDP 192.168.1.112:68 
systemd-r 460 systemd-resolve   12u  IPv4  16107      0t0  UDP 127.0.0.53:53 
sshd      540            root    4u  IPv6  17935      0t0  TCP *:22 (LISTEN)

Tested on Ubuntu 18.04.1 and Debian 9.

**Comment by f0rb1dd3n** [comment]
I am going to analyse this soon.

Thanks for reporting 👍

**Comment by corefx** [comment]
Works fine with Ubuntu 18.04.1 and Debian 9. Thanks for fixing this. :+1:
