### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by MRchen532** [f0rb1dd3n/Reptile#56]
So, to install on this Centos you just need to run `./setup.sh install`. But before you will have to install String::Unescape perl module. 

To do that, normally is just do this command or even `cpan -i String::Unescape`. But if you are having problem with that, you will have to check your perl. Maybe in some configurations, perl is not fully installed. 

Try to install (or even reinstall) perl and cpan in your system: `yum install perl-devel cpan`

Is also recommended: `yum update`

_Originally posted by @f0rb1dd3n in https://github.com/f0rb1dd3n/Reptile/issues/54#issuecomment-445331735_

**Comment by f0rb1dd3n** [comment]
I am closing this because this subject is being discussed in #54
