### ISSUE TITLE
How to make it?

### ISSUE THREAD

**Issue by wjcgy** [f0rb1dd3n/Reptile#59]
[cgy@localhost Reptile-master]$ make
mkdir -p bin
cd sbin && make reverse cmd
make[1]: Enter the directory“/home/cgy/desktop/Reptile-master/sbin”
cat reverse.c | perl ../scripts/destringify.pl | gcc -O -W -Wall -o reverse pel.c aes.c sha1.c  -D_REPTILE_ -xc - -lutil
<stdin>:15:20: Fatal error：config.h：No such file or directory
Compile interrupt。
make[1]: *** [reverse] error 1
make[1]: Leave the directory“/home/cgy/desktop/Reptile-master/sbin”
make: *** [all] error 2

**Comment by f0rb1dd3n** [comment]
please, read the README.md file and [Wiki](https://github.com/f0rb1dd3n/Reptile/wiki/Usage) before before this kind of question.

thank you.

**Comment by pyperanger** [comment]
RTFM

**Comment by zioncorp77** [comment]
I too am having the same problem event when i sudo ./setup.sh install.... make gives me the same error as above. sudo ./setup.sh client compiles no problem. Is that it than? ./setup.sh client? whats ./setup.sh install for than? am I missing something your wiki is kind of confusing....in the readme it says to ./setup.sh install in the wiki it says ./setup client which one is it?? and am i suppose to be running the client from my machine? or the box i am trying to install the rootkit on....sorry if i sound like a noob....
