### ISSUE TITLE
CPAN used too much resources.

### ISSUE THREAD

**Issue by aliyuchang33** [f0rb1dd3n/Reptile#60]
My pool machine cannot install the cpan module because cpan is killed during the process. I found a solution to use cpanm from https://stackoverflow.com/questions/11108029/cpan-shell-runs-out-of-memory-how-can-i-give-it-more-memory-on-unix/11110491#11110491. Any plan to get rid of cpan dependency?

**Comment by aliyuchang33** [comment]
And still no response from server. Many tries.

**Comment by f0rb1dd3n** [comment]
I will think about CPAN dependency, it is really inconvenient. And thx for reporting about srchost, I am going to take a look into that.

**Comment by f0rb1dd3n** [comment]
I will comment here some things:

I did some tests with SRCHOST spoofing, and all gone right. I think this kind of problems is getting when you are outside a firewall, trying to send the magic packet through NAT. 

I got problems with SRCHOST only in this case, when i tried to sent through NAT. Inside a local network, all went right
