### ISSUE TITLE
how to update the reptile without reboot?

### ISSUE THREAD

**Issue by a4626219** [f0rb1dd3n/Reptile#63]
hello,is there anyway to update the reptile without reoot?
I can't install before remove reptile,but remove it need reboot.

**Comment by f0rb1dd3n** [comment]
So, yeah, there is a way to unload the module, and then load a new updated one. 

I will consider that in the next commits

**Comment by a4626219** [comment]
@f0rb1dd3n  was it done?

**Comment by f0rb1dd3n** [comment]
@a4626219 sorry my huuuuuuuge delay. For newer versions of khook, Reptile can be uninstalled without rebooting, but i know there is a lot of bugs which can force you reboot when uninstalling reptile. In other words, it is not full done. 

I didn't find time to code Reptile last year. But maybe I am going to update this project when it is possible (which means, slowly, hahahahah)

**Comment by f0rb1dd3n** [comment]
So, you can do the Uninstallation of reptile with this new commit: 6bd476e

If you wanna update, it's just uninstall, download the code, build and install again!
