### ISSUE TITLE
can't hide udp port??

### ISSUE THREAD

**Issue by koushui** [f0rb1dd3n/Reptile#67]
Thanks to the author,Good job,very cool~!
but,can't hide udp port??
i try "/reptile/reptile_cmd conn <IP> <port> hide" hiden a udp listen，only hide TCP PORT,hide udp  not work! 

By the way, if can increase access to SSH, SSHD password keylogger features, the same with command line switch, then a more perfect~!

**Comment by f0rb1dd3n** [comment]
Thanks your words man. 

So, about the udp connection hiding, I will consider add this feature in next commits. About SSH keylogger, I am not sure yet, even cause you can do some `strace` and get the clean text password (and hide the strace process with reptile).

**Comment by f0rb1dd3n** [comment]
I just added UDP hiding feature on this commit 165b539.

so, check it out!

**Comment by koushui** [comment]
3X ，Test is OK~!
