### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YuroSh** [f0rb1dd3n/Reptile#68]
Thank you for this amazing rootkit that works perfectly, but why not add public network support ? 
It would be much better :)

**Comment by f0rb1dd3n** [comment]
Thanks man, what did you mean about "public network support"?

**Comment by YuroSh** [comment]
I mean WAN because for me it only works in a local network

**Comment by f0rb1dd3n** [comment]
This rootkit is supposed to work from the Internet (if it is you wanna know). But it will follow the NAT rules, in other words you will have a little bit of limitation.

**Comment by YuroSh** [comment]
Thanks bro ^^
