### ISSUE TITLE
About Unknown symbol

### ISSUE THREAD

**Issue by rtw49418** [f0rb1dd3n/Reptile#69]
test on GCP centos 3.10.0-693.21.1.el7.x86_64
`
eptile: Unknown symbol sme_me_mask (err 0)
eptile: Unknown symbol __check_object_size (err 0)
eptile: Unknown symbol sme_me_mask (err 0)
eptile: Unknown symbol __check_object_size (err 0)
eptile: Unknown symbol sme_me_mask (err 0)
eptile: Unknown symbol __check_object_size (err 0)
`

how to slove this?

**Comment by f0rb1dd3n** [comment]
thank you for reporting that, I am going to fix it

**Comment by f0rb1dd3n** [comment]
So I fixed it on this commit (165b539)[https://github.com/f0rb1dd3n/Reptile/commit/165b5394f27510e4a0831bedbb8a1e15c370a437]

check it out

**Comment by xroot000** [comment]
now connection hiding does not work..

**Comment by f0rb1dd3n** [comment]
I don't think so:

```
root@centos:/root# uname -a
Linux centos 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@centos:/root# netstat | grep 172.16.65.234
tcp        0      0 centos:48992            172.16.65.234:krb524    ESTABLISHED
root@centos:/root# /reptile/reptile_cmd tcp 172.16.65.234 4444 hide
Success!
root@centos:/root# netstat | grep 172.16.65.234
root@centos:/root# 
```

**Comment by xroot000** [comment]
with last commits I got "Failed" but not "Success"
if I use the code I downloaded 3 days ago - everithing OK

**Comment by xroot000** [comment]
hmmm
I don't used "tcp" word before..
Ok, will try

**Comment by xroot000** [comment]
yeah, its ok
fix wiki about this new feature than, pls)
