### ISSUE TITLE
Is there any way to forge CPU usage?I don't want people to see the real CPU load by command

### ISSUE THREAD

**Issue by caojioayue** [f0rb1dd3n/Reptile#75]
Is there any way to forge CPU usage?I don't want people to see the real CPU load by command

**Comment by f0rb1dd3n** [comment]
yeah, there is. But I have it in private.

**Comment by caojioayue** [comment]
Can eldest brother share it with me? I've been looking for this for a long time.

**Comment by caojioayue** [comment]
Is it implemented by LD_PRELOAD?

**Comment by f0rb1dd3n** [comment]
Please mail me to discuss details about it. And it is not using LD_PRELOAD, it is kernel stuff

**Comment by caojioayue** [comment]
this is my mail 979477675@qq.com can you send hide cpu usage code to me? Thank  I hide process by LD_PRELOAD if you need i can send to your mail

**Comment by f0rb1dd3n** [comment]
mail me man. I am busy. So, i am not interested on LD_PRELOAD stuff, I know how it works, and I already have stuff like that.

**Comment by f0rb1dd3n** [comment]
btw, f0rb1dd3n@tuta.io

**Comment by caojioayue** [comment]
I sent you a message by email
