### ISSUE TITLE
Centos kernel v4

### ISSUE THREAD

**Issue by elliot-sy** [f0rb1dd3n/Reptile#76]
Hello,

rootkit runs smooth on latest kernel tested on Centos kernel v4.x.

Once machine reboot rootkit didn't work anymore.

**Comment by f0rb1dd3n** [comment]
Hello,

sorry my late reply, I am going to take a look at it soon.

thank you

**Comment by f0rb1dd3n** [comment]
I tested this on CentOS 8, and Reptile is running. So, could you test it and tell me if it is working for you?

**Comment by f0rb1dd3n** [comment]
I fixed the persistence issue with 6bd476e, see if it's working for you!
