### ISSUE TITLE
Kernel Crash after unloading module

### ISSUE THREAD

**Issue by mrunc** [f0rb1dd3n/Reptile#8]
I get a crash after unloading module looks like memory corruption
"BUG: unable to handle kernel paging request at ffffffffc06e69bb"
It has something to do with file content hiding feature it doesn't crash after commenting all related functions
this is on CentOS 7 3.10.0-693.5.2.el7.x86_64

**Comment by f0rb1dd3n** [comment]
hello, I did various tests on most recent CentOS version, and I didnt get this crash. Could you give more information about that? Thank you very much

**Comment by mrunc** [comment]
It's weird I was testing with CentOS VM with Vmware-Tools packaged version now on a clean install with open-vm-tools installed it's working fine and no memory corruption

**Comment by f0rb1dd3n** [comment]
very nice man! I am glad your test doesn't crash anymore. May you close this issue?

greetings

**Comment by mrunc** [comment]
Now I'm sure about this bug if you disabled kdump you won't notice it but it exist in file content hiding functions

On CentOS 7.4 with kdump enabled

# systemctl start kdump
# ./installer install

and then unhide & unload

# kill -50 0 && rmmod reptile_mod

wait a few seconds and your shell will crash and when you open a new ssh connection you get 
ABRT has detected 1 problem(s). For more info run: abrt-cli list

# abrt-cli list
id e2891116ff93c3977b553dd4166eb019ae36ca4c
reason:         BUG: unable to handle kernel paging request at ffffffffc06ba9bb
time:           Sat 16 Dec 2017 02:36:05 PM EET
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/vmcore-127.0.0.1-2017-12-16-14:35:45
Reported:       cannot be reported

**Comment by f0rb1dd3n** [comment]
Hello man,

I did some updates about bugs. Can you test if you will get this error again?

thanks

**Comment by f0rb1dd3n** [comment]
Hello @mrunc, is this bug fixed? Can we close this issue?

thx

**Comment by mrunc** [comment]
yes the crash is fixed now
Thanks
