### ISSUE TITLE
hide process error in centos6.8

### ISSUE THREAD

**Issue by wulasite** [f0rb1dd3n/Reptile#81]
the kernel version: 2.6.32-642.el6.x86_64
I think it will work in this kernel . but when I run 
` /reptile/reptile_cmd hide 2992`
it return 
`Failed!`
the pid just a nohup ping process.I have  test it in ubuntu18.04.
I see you have test in 2.6.32-754.6.3.el6.x86_64, but why it doesn't work in 2.6.32-642

**Comment by wulasite** [comment]
I reinstall the system and kernel-devel. it work.

**Comment by f0rb1dd3n** [comment]
I haven't had the chance of answer, hahaha, but thank you for sharing your solution. I am glad to hear it still working in oldest kernels in CentOS 6.

**Comment by wulasite** [comment]
> I haven't had the chance of answer, hahaha, but thank you for sharing your solution. I am glad to hear it still working in oldest kernels in CentOS 6.

today I found the reason. the centos open the selinux default. when use the script , it will closed the change the selinux config,but it will not close the selinux. So I have to reboot or run setenforce 0, then it work. I think you can add "setenforce 0" to the script.

**Comment by wulasite** [comment]
> I haven't had the chance of answer, hahaha, but thank you for sharing your solution. I am glad to hear it still working in oldest kernels in CentOS 6.

I think the reason is the kernel-devel dependency.my centos kernel is 2.6.32-642.But when I run "yum -y install kernel-devel.x86_64" , the version is 754. But I don't know how to install 642 version through yum , so I use the rpm.
